name: Test and build

on: [pull_request_target]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: aukilabs/go-tooling/.github/workflows/tests.yml@main
    with:
      enable_coverage: true
      enable_integration_tests: true
      enable_tunnel: true
    secrets:
      ngrok_auth_token: ${{ vars.GLOBAL_PUBLIC_NGROK_AUTH_TOKEN }}
  build:
    name: Build
    uses: aukilabs/go-tooling/.github/workflows/build.yml@main
  custom:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "the ref: ${{ github.ref_name }}"
          echo "more echo"
          


