name: Test and build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: aukilabs/go-tooling/.github/workflows/tests.yml@main
    with:
      enable_coverage: true
  build:
    name: Build
    uses: aukilabs/go-tooling/.github/workflows/build.yml@main

