apiVersion: v1
kind: Service
metadata:
  name: {{ include "hagall.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hagall.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "hagall.selectorLabels" . | nindent 4 }}
  ports:
    - name: admin
      protocol: TCP
      port: 9090
      targetPort: admin
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: metrics
